<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <!--<Platform Condition=" '$(Platform)' == '' ">x86</Platform>-->
    <OutputType>Library</OutputType>
    <RootNamespace>DDL_Parser</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <!--<Reference Update="System.Core">
      <RequiredTargetFramework>3.5</RequiredTargetFramework>
    </Reference>
    <Reference Update="System.Xml.Linq">
      <RequiredTargetFramework>3.5</RequiredTargetFramework>
    </Reference>-->
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
  </ItemGroup>
</Project>